# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('tease', models.TextField(blank=True, verbose_name='Tease(summary)')),
                ('body', models.TextField(verbose_name='Content')),
                ('draft', models.BooleanField(default=True, verbose_name='Is draft')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'published')], default='d', max_length=1)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of creation')),
                ('published_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of publication')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ('-published_date',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='BafosApp.Category'),
        ),
    ]
