# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BafosApp', '0002_remove_blogpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'published')], default='d', max_length=1),
        ),
    ]
