# Generated by Django 2.1.1 on 2018-09-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BafosApp', '0004_auto_20180904_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
